version: '3.2'

services:
  db:
    image: bitnami/postgresql:11.8.0-debian-10-r1
    env_file: .env
    restart: always
    volumes:
      - ./data/pg:/bitnami/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
